// Static/dummy data for the Drishya UI. Swap with API responses later.
import type {
  Alert,
  AuditEntry,
  Camera,
  DashboardStats,
  NamedCount,
  TimePoint,
  User,
} from "./types";

export const cameras: Camera[] = [
  {
    id: "cam-01",
    name: "Camera 01",
    location: "Main Gate",
    zone: "Perimeter",
    status: "online",
    streamUrl: "rtsp://10.0.0.11:554/stream1",
    aiEnabled: true,
    detections: ["person", "vehicle"],
    lastDetection: "person",
    lastConfidence: 92,
    boxes: [
      { x: 38, y: 30, w: 16, h: 42, label: "person", confidence: 92 },
      { x: 62, y: 52, w: 26, h: 28, label: "vehicle", confidence: 81 },
    ],
  },
  {
    id: "cam-02",
    name: "Camera 02",
    location: "Parking Lot A",
    zone: "Parking",
    status: "online",
    streamUrl: "rtsp://10.0.0.12:554/stream1",
    aiEnabled: true,
    detections: ["vehicle"],
    lastDetection: "vehicle",
    lastConfidence: 78,
    boxes: [{ x: 30, y: 44, w: 34, h: 32, label: "vehicle", confidence: 78 }],
  },
  {
    id: "cam-03",
    name: "Camera 03",
    location: "Reception",
    zone: "Indoor",
    status: "online",
    streamUrl: "rtsp://10.0.0.13:554/stream1",
    aiEnabled: true,
    detections: ["person", "crowd"],
    lastDetection: "crowd",
    lastConfidence: 84,
    boxes: [
      { x: 20, y: 38, w: 14, h: 40, label: "person", confidence: 88 },
      { x: 40, y: 40, w: 13, h: 38, label: "person", confidence: 79 },
      { x: 58, y: 42, w: 14, h: 36, label: "person", confidence: 76 },
    ],
  },
  {
    id: "cam-04",
    name: "Camera 04",
    location: "Back Door",
    zone: "Perimeter",
    status: "online",
    streamUrl: "rtsp://10.0.0.14:554/stream1",
    aiEnabled: true,
    detections: ["intrusion", "person"],
    lastDetection: "intrusion",
    lastConfidence: 95,
    boxes: [{ x: 44, y: 26, w: 18, h: 50, label: "intrusion", confidence: 95 }],
  },
  {
    id: "cam-05",
    name: "Camera 05",
    location: "Warehouse",
    zone: "Storage",
    status: "online",
    streamUrl: "rtsp://10.0.0.15:554/stream1",
    aiEnabled: true,
    detections: ["fire"],
    lastDetection: "fire",
    lastConfidence: 88,
    boxes: [{ x: 55, y: 50, w: 22, h: 28, label: "fire", confidence: 88 }],
  },
  {
    id: "cam-06",
    name: "Camera 06",
    location: "Corridor B",
    zone: "Indoor",
    status: "offline",
    streamUrl: "rtsp://10.0.0.16:554/stream1",
    aiEnabled: false,
    detections: [],
  },
  {
    id: "cam-07",
    name: "Camera 07",
    location: "Loading Bay",
    zone: "Storage",
    status: "online",
    streamUrl: "rtsp://10.0.0.17:554/stream1",
    aiEnabled: true,
    detections: ["vehicle", "person"],
    lastDetection: "vehicle",
    lastConfidence: 73,
    boxes: [{ x: 26, y: 40, w: 40, h: 36, label: "vehicle", confidence: 73 }],
  },
  {
    id: "cam-08",
    name: "Camera 08",
    location: "Perimeter West",
    zone: "Perimeter",
    status: "online",
    streamUrl: "rtsp://10.0.0.18:554/stream1",
    aiEnabled: true,
    detections: ["suspicious", "person"],
    lastDetection: "suspicious",
    lastConfidence: 67,
    boxes: [{ x: 48, y: 30, w: 16, h: 46, label: "suspicious", confidence: 67 }],
  },
  {
    id: "cam-09",
    name: "Camera 09",
    location: "Server Room",
    zone: "Restricted",
    status: "online",
    streamUrl: "rtsp://10.0.0.19:554/stream1",
    aiEnabled: true,
    detections: ["person"],
    lastDetection: undefined,
    lastConfidence: undefined,
  },
  {
    id: "cam-10",
    name: "Camera 10",
    location: "Parking Lot B",
    zone: "Parking",
    status: "online",
    streamUrl: "rtsp://10.0.0.20:554/stream1",
    aiEnabled: true,
    detections: ["vehicle", "weapon"],
    lastDetection: "weapon",
    lastConfidence: 91,
    boxes: [{ x: 40, y: 48, w: 18, h: 16, label: "weapon", confidence: 91 }],
  },
  {
    id: "cam-11",
    name: "Camera 11",
    location: "Lobby",
    zone: "Indoor",
    status: "online",
    streamUrl: "rtsp://10.0.0.21:554/stream1",
    aiEnabled: true,
    detections: ["person", "crowd"],
    lastDetection: "person",
    lastConfidence: 82,
    boxes: [{ x: 34, y: 36, w: 15, h: 42, label: "person", confidence: 82 }],
  },
  {
    id: "cam-12",
    name: "Camera 12",
    location: "Rooftop",
    zone: "Perimeter",
    status: "offline",
    streamUrl: "rtsp://10.0.0.22:554/stream1",
    aiEnabled: false,
    detections: [],
  },
];

export const alerts: Alert[] = [
  {
    id: "alt-1042",
    time: "2026-06-19T10:24:00",
    cameraId: "cam-10",
    cameraName: "Camera 10",
    location: "Parking Lot B",
    detection: "weapon",
    severity: "critical",
    confidence: 91,
    status: "new",
  },
  {
    id: "alt-1041",
    time: "2026-06-19T10:18:00",
    cameraId: "cam-04",
    cameraName: "Camera 04",
    location: "Back Door",
    detection: "intrusion",
    severity: "high",
    confidence: 95,
    status: "reviewing",
    assignedTo: "Priya N.",
  },
  {
    id: "alt-1040",
    time: "2026-06-19T10:05:00",
    cameraId: "cam-05",
    cameraName: "Camera 05",
    location: "Warehouse",
    detection: "fire",
    severity: "critical",
    confidence: 88,
    status: "confirmed",
    assignedTo: "Arjun R.",
    note: "Smoke confirmed near rack 4. Fire response notified.",
  },
  {
    id: "alt-1039",
    time: "2026-06-19T09:55:00",
    cameraId: "cam-08",
    cameraName: "Camera 08",
    location: "Perimeter West",
    detection: "suspicious",
    severity: "medium",
    confidence: 67,
    status: "new",
  },
  {
    id: "alt-1038",
    time: "2026-06-19T09:41:00",
    cameraId: "cam-01",
    cameraName: "Camera 01",
    location: "Main Gate",
    detection: "person",
    severity: "low",
    confidence: 92,
    status: "resolved",
  },
  {
    id: "alt-1037",
    time: "2026-06-19T09:30:00",
    cameraId: "cam-02",
    cameraName: "Camera 02",
    location: "Parking Lot A",
    detection: "vehicle",
    severity: "low",
    confidence: 78,
    status: "false_alarm",
    note: "Delivery van, scheduled.",
  },
  {
    id: "alt-1036",
    time: "2026-06-19T09:12:00",
    cameraId: "cam-03",
    cameraName: "Camera 03",
    location: "Reception",
    detection: "crowd",
    severity: "medium",
    confidence: 84,
    status: "resolved",
    assignedTo: "Priya N.",
  },
  {
    id: "alt-1035",
    time: "2026-06-19T08:58:00",
    cameraId: "cam-07",
    cameraName: "Camera 07",
    location: "Loading Bay",
    detection: "vehicle",
    severity: "low",
    confidence: 73,
    status: "resolved",
  },
  {
    id: "alt-1034",
    time: "2026-06-19T08:40:00",
    cameraId: "cam-04",
    cameraName: "Camera 04",
    location: "Back Door",
    detection: "person",
    severity: "medium",
    confidence: 81,
    status: "resolved",
  },
  {
    id: "alt-1033",
    time: "2026-06-19T08:22:00",
    cameraId: "cam-11",
    cameraName: "Camera 11",
    location: "Lobby",
    detection: "person",
    severity: "low",
    confidence: 82,
    status: "resolved",
  },
  {
    id: "alt-1032",
    time: "2026-06-19T08:05:00",
    cameraId: "cam-10",
    cameraName: "Camera 10",
    location: "Parking Lot B",
    detection: "vehicle",
    severity: "low",
    confidence: 70,
    status: "false_alarm",
  },
  {
    id: "alt-1031",
    time: "2026-06-19T07:48:00",
    cameraId: "cam-08",
    cameraName: "Camera 08",
    location: "Perimeter West",
    detection: "intrusion",
    severity: "high",
    confidence: 89,
    status: "confirmed",
    assignedTo: "Arjun R.",
    note: "Fence breach attempt, guard dispatched.",
  },
];

export const users: User[] = [
  {
    id: "usr-1",
    name: "Arjun Rao",
    email: "arjun@nammacctv.com",
    role: "admin",
    status: "active",
    lastActive: "2026-06-19T10:20:00",
  },
  {
    id: "usr-2",
    name: "Priya Nair",
    email: "priya@nammacctv.com",
    role: "operator",
    status: "active",
    lastActive: "2026-06-19T10:18:00",
  },
  {
    id: "usr-3",
    name: "Karthik S.",
    email: "karthik@nammacctv.com",
    role: "operator",
    status: "active",
    lastActive: "2026-06-19T09:02:00",
  },
  {
    id: "usr-4",
    name: "Meera Iyer",
    email: "meera@nammacctv.com",
    role: "viewer",
    status: "disabled",
    lastActive: "2026-06-12T17:44:00",
  },
];

export const auditLog: AuditEntry[] = [
  {
    id: "aud-1",
    time: "2026-06-19T10:25:00",
    actor: "Priya Nair",
    action: "Marked alert as Reviewing",
    target: "alt-1041",
  },
  {
    id: "aud-2",
    time: "2026-06-19T10:06:00",
    actor: "Arjun Rao",
    action: "Confirmed incident",
    target: "alt-1040",
  },
  {
    id: "aud-3",
    time: "2026-06-19T09:31:00",
    actor: "Priya Nair",
    action: "Marked as False Alarm",
    target: "alt-1037",
  },
  {
    id: "aud-4",
    time: "2026-06-19T08:50:00",
    actor: "Arjun Rao",
    action: "Viewed camera feed",
    target: "cam-09 (Server Room)",
  },
];

export const stats: DashboardStats = {
  totalCameras: 12,
  activeCameras: 10,
  alertsToday: 34,
  criticalAlerts: 3,
  serverStatus: "online",
  storageUsedPct: 62,
  modelHealthPct: 97,
};

export const alertsOverTime: TimePoint[] = [
  { label: "00:00", alerts: 2, critical: 0 },
  { label: "03:00", alerts: 1, critical: 0 },
  { label: "06:00", alerts: 4, critical: 1 },
  { label: "08:00", alerts: 7, critical: 1 },
  { label: "10:00", alerts: 11, critical: 2 },
  { label: "12:00", alerts: 6, critical: 0 },
  { label: "14:00", alerts: 3, critical: 0 },
];

export const alertsByCamera: NamedCount[] = [
  { name: "Cam 04", value: 9 },
  { name: "Cam 10", value: 7 },
  { name: "Cam 08", value: 6 },
  { name: "Cam 01", value: 5 },
  { name: "Cam 05", value: 4 },
  { name: "Cam 03", value: 3 },
];

export const alertsByType: NamedCount[] = [
  { name: "Person", value: 14 },
  { name: "Vehicle", value: 9 },
  { name: "Intrusion", value: 5 },
  { name: "Fire", value: 2 },
  { name: "Weapon", value: 2 },
  { name: "Crowd", value: 2 },
];
